"""empty message

Revision ID: b2a4b30fdece
Revises: 0a6d3d1508a5
Create Date: 2021-03-04 18:52:11.795274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a4b30fdece'
down_revision = '0a6d3d1508a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=60), nullable=True),
    sa.Column('complaint', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('registeredAdmin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registeredAdmin'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaintLocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaintID', sa.Integer(), nullable=True),
    sa.Column('lng', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['complaintID'], ['complaint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaintLocation')
    op.drop_table('complaint')
    # ### end Alembic commands ###
